// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: transaction.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskChecker_TransScrutiny_FullMethodName = "/RiskChecker/TransScrutiny"
)

// RiskCheckerClient is the client API for RiskChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskCheckerClient interface {
	TransScrutiny(ctx context.Context, in *TransRequest, opts ...grpc.CallOption) (*TransResponce, error)
}

type riskCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskCheckerClient(cc grpc.ClientConnInterface) RiskCheckerClient {
	return &riskCheckerClient{cc}
}

func (c *riskCheckerClient) TransScrutiny(ctx context.Context, in *TransRequest, opts ...grpc.CallOption) (*TransResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransResponce)
	err := c.cc.Invoke(ctx, RiskChecker_TransScrutiny_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskCheckerServer is the server API for RiskChecker service.
// All implementations must embed UnimplementedRiskCheckerServer
// for forward compatibility.
type RiskCheckerServer interface {
	TransScrutiny(context.Context, *TransRequest) (*TransResponce, error)
	mustEmbedUnimplementedRiskCheckerServer()
}

// UnimplementedRiskCheckerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskCheckerServer struct{}

func (UnimplementedRiskCheckerServer) TransScrutiny(context.Context, *TransRequest) (*TransResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransScrutiny not implemented")
}
func (UnimplementedRiskCheckerServer) mustEmbedUnimplementedRiskCheckerServer() {}
func (UnimplementedRiskCheckerServer) testEmbeddedByValue()                     {}

// UnsafeRiskCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskCheckerServer will
// result in compilation errors.
type UnsafeRiskCheckerServer interface {
	mustEmbedUnimplementedRiskCheckerServer()
}

func RegisterRiskCheckerServer(s grpc.ServiceRegistrar, srv RiskCheckerServer) {
	// If the following call pancis, it indicates UnimplementedRiskCheckerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskChecker_ServiceDesc, srv)
}

func _RiskChecker_TransScrutiny_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskCheckerServer).TransScrutiny(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskChecker_TransScrutiny_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskCheckerServer).TransScrutiny(ctx, req.(*TransRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskChecker_ServiceDesc is the grpc.ServiceDesc for RiskChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RiskChecker",
	HandlerType: (*RiskCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransScrutiny",
			Handler:    _RiskChecker_TransScrutiny_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction.proto",
}
