// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      int32                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Amount        int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	TransferType  bool                   `protobuf:"varint,5,opt,name=transfer_type,json=transferType,proto3" json:"transfer_type,omitempty"`
	FromId        string                 `protobuf:"bytes,6,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId          string                 `protobuf:"bytes,7,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransRequest) Reset() {
	*x = TransRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransRequest) ProtoMessage() {}

func (x *TransRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransRequest.ProtoReflect.Descriptor instead.
func (*TransRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransRequest) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TransRequest) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TransRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransRequest) GetTransferType() bool {
	if x != nil {
		return x.TransferType
	}
	return false
}

func (x *TransRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *TransRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

type TransResponce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOk          bool                   `protobuf:"varint,1,opt,name=is_ok,json=isOk,proto3" json:"is_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransResponce) Reset() {
	*x = TransResponce{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransResponce) ProtoMessage() {}

func (x *TransResponce) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransResponce.ProtoReflect.Descriptor instead.
func (*TransResponce) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransResponce) GetIsOk() bool {
	if x != nil {
		return x.IsOk
	}
	return false
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\"\xcc\x01\n" +
	"\fTransRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x05R\tlongitude\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12#\n" +
	"\rtransfer_type\x18\x05 \x01(\bR\ftransferType\x12\x17\n" +
	"\afrom_id\x18\x06 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\a \x01(\tR\x04toId\"$\n" +
	"\rTransResponce\x12\x13\n" +
	"\x05is_ok\x18\x01 \x01(\bR\x04isOk2?\n" +
	"\vRiskChecker\x120\n" +
	"\rTransScrutiny\x12\r.TransRequest\x1a\x0e.TransResponce\"\x00B(Z&github.com/IdentityStolen/RiskOS/protob\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_proto_goTypes = []any{
	(*TransRequest)(nil),  // 0: TransRequest
	(*TransResponce)(nil), // 1: TransResponce
}
var file_transaction_proto_depIdxs = []int32{
	0, // 0: RiskChecker.TransScrutiny:input_type -> TransRequest
	1, // 1: RiskChecker.TransScrutiny:output_type -> TransResponce
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
